/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FatiasRouteImport } from './routes/fatias'
import { Route as MarcosRouteImport } from './routes/marcos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FatiasRoute = FatiasRouteImport.update({
  id: '/fatias',
  path: '/fatias',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcosRoute = MarcosRouteImport.update({
  id: '/marcos',
  path: '/marcos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fatias': typeof FatiasRoute
  '/marcos': typeof MarcosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fatias': typeof FatiasRoute
  '/marcos': typeof MarcosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fatias': typeof FatiasRoute
  '/marcos': typeof MarcosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fatias' | '/marcos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fatias' | '/marcos'
  id: '__root__' | '/' | '/fatias' | '/marcos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FatiasRoute: typeof FatiasRoute
  MarcosRoute: typeof MarcosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatias': {
      id: '/fatias'
      path: '/fatias'
      fullPath: '/fatias'
      preLoaderRoute: typeof FatiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcos': {
      id: '/marcos'
      path: '/marcos'
      fullPath: '/marcos'
      preLoaderRoute: typeof MarcosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FatiasRoute: FatiasRoute,
  MarcosRoute: MarcosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
